Run pre-commit hook only on staged files

diff --git a/.githooks/pre-commit b/.githooks/pre-commit
--- a/.githooks/pre-commit
+++ b/.githooks/pre-commit
@@ -1,16 +1,26 @@
 #!/bin/bash
 
-vendor/bin/phpcs -d memory_limit=512M --standard=phpcs.xml.dist
-if [ $? -ne 0 ]; then
-  echo "PHP_CodeSniffer failed. Please fix the errors."
-  exit 1
+# Get staged PHP files for PHP CodeSniffer
+php_files=$(git diff --cached --name-only --diff-filter=ACM | grep -E '\.php$')
+if [ -n "$php_files" ]; then
+  echo "Running PHP CodeSniffer on the following files:"
+  echo "$php_files"
+
+  echo "$php_files" | xargs vendor/bin/phpcs -d memory_limit=512M --standard=phpcs.xml.dist
+  if [ $? -ne 0 ]; then
+    echo "PHP CodeSniffer failed. Please fix the errors."
+    exit 1
+  fi
 fi
 
-js_files=$(git diff --cached --name-only --diff-filter=ACM | grep -E '^(js/.*\.js)$')
+# Get staged CSS and JS files
 css_files=$(git diff --cached --name-only --diff-filter=ACM | grep -E '^(css/.*\.css)$')
+js_files=$(git diff --cached --name-only --diff-filter=ACM | grep -E '^(js/.*\.js)$')
 
-all_files="$js_files $css_files"
+# Combine CSS and JS files into a single variable
+all_files="$css_files $js_files"
 
+# Run Prettier if there are CSS or JS files
 if [ -n "$all_files" ]; then
   echo "Running Prettier on the following files:"
   echo "$all_files"
@@ -21,6 +31,7 @@ if [ -n "$all_files" ]; then
     exit 1
   fi
 
+  # Add formatted files back to the staged changes
   echo "$all_files" | xargs git add
 fi
 
